steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/dicsord-voice-assistant:${SHORT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/dicsord-voice-assistant"]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'dicsord-voice-assistant', '--image', 'gcr.io/$PROJECT_ID/dicsord-voice-assistant:${SHORT_SHA}', '--region', 'us-central1', '--platform', 'managed']
timeout: '1600s'
